// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tpi.DBContexts;

#nullable disable

namespace tpi.Migrations
{
    [DbContext(typeof(AppTPIContext))]
    partial class AppTPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("tpi.Entities.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoPersonaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TipoPersonaId");

                    b.ToTable("Personas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "superadmin@email.com",
                            Name = "Esteban Quito",
                            Password = "superadmin",
                            TipoPersonaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "admin@email.com",
                            Name = "Igor Dito",
                            Password = "admin",
                            TipoPersonaId = 2
                        },
                        new
                        {
                            Id = 3,
                            Email = "user@email.com",
                            Name = "Armando Escandalo",
                            Password = "user",
                            TipoPersonaId = 3
                        });
                });

            modelBuilder.Entity("tpi.Entities.TipoPersona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TiposPersona");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Tipo = "Super Admin"
                        },
                        new
                        {
                            Id = 2,
                            Tipo = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            Tipo = "Usuario"
                        });
                });

            modelBuilder.Entity("tpi.Entities.Persona", b =>
                {
                    b.HasOne("tpi.Entities.TipoPersona", "TipoPersona")
                        .WithMany()
                        .HasForeignKey("TipoPersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoPersona");
                });
#pragma warning restore 612, 618
        }
    }
}
